name: instax
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.6
  

  flutter:
    sdk: flutter

  #firebase
  firebase_core: ^4.1.1
  firebase_auth: ^6.1.0

  #bloc
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7

 #custom repository
  user_repository:
    path: packages/user_repository

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
